### ISSUE TITLE
Proposed Debt exceed max value for collateral error in Wallet UI when submitting vault creation offer

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-inter#113]
## Describe the bug

Getting below error in Wallet UI upon attempting to approve vault creation transaction (following txn signing in Keplr):

![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/ce01a8f5-144c-4e1d-b65d-a67e036c5ab0)

## To Reproduce

1. Go to Vaults UI
2. Submit create vault offer
3. Approve in Wallet UI
4. Sign Keplr transaction
5. Get error

## Expected behavior

Vault should be created

## Platform Environment

- what OS are you using? what version of Node.js?
- is there anything special/unusual about your platform?
- what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots

If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by samsiegart** [comment]
More context: The UI displays a price of 14.5, with 175% MCR. The numbers in the screenshot above appear to be enforcing a price of 0.151, which was the result of a previous price round. However, the price was since updated to 14.5, which the UI sees, but the contract doesn't seem to be enforcing.

@turadg @dckc I'm soliciting some input here, I'm thinking either the UI or the contract is reading the price from the wrong source. The UI is watching [manager0.quotes](https://github.com/Agoric/dapp-inter/blob/main/src/service/vaults.ts#L72), is that correct? How can we make sure the contract and UI are in sync?

**Comment by rowgraus** [comment]
Observed an apparent manifestation of this error again in attempting to test liquidation.
Ran through scenario with three vaults where updating the price to 9.99 was meant to trigger liquidation.  UI saw price update correctly but the auction started based on the price being 14.5 (apparently a previous price, visible in the CLI)

**Comment by rowgraus** [comment]
Still seeing this issue which is blocking testing

**Comment by rowgraus** [comment]
Created issue in agoric-sdk (7670).  Closing this issue in favor of that
